#pragma once

#define STEP_PER_ROUND 200
#define MOTOR1_STEP_PER_ROUND STEP_PER_ROUND
#define MOTOR2_STEP_PER_ROUND STEP_PER_ROUND
#define MOTOR3_STEP_PER_ROUND STEP_PER_ROUND
#define MOTOR4_STEP_PER_ROUND STEP_PER_ROUND
#define MOTOR5_STEP_PER_ROUND STEP_PER_ROUND

#define MAX_PLANNER_SPEED 20000
#define PLANNER_ACCELERATION 1000
