#pragma once

#define STEP_PER_ROUND 200
#define MOTOR1_STEP_PER_ROUND STEP_PER_ROUND
#define MOTOR2_STEP_PER_ROUND STEP_PER_ROUND
#define MOTOR3_STEP_PER_ROUND STEP_PER_ROUND
#define MOTOR4_STEP_PER_ROUND STEP_PER_ROUND
#define MOTOR5_STEP_PER_ROUND STEP_PER_ROUND

#define DRV_MICROSTEPPING 16
#define DRV1_MICROSTEPPING DRV_MICROSTEPPING
#define DRV2_MICROSTEPPING DRV_MICROSTEPPING
#define DRV3_MICROSTEPPING DRV_MICROSTEPPING
#define DRV4_MICROSTEPPING DRV_MICROSTEPPING
#define DRV5_MICROSTEPPING DRV_MICROSTEPPING

#define MAX_PLANNER_SPEED 20000
#define PLANNER_ACCELERATION 1000
