#pragma once

#define STEP_PER_ROUND 200
#define MOTOR1_STEP_PER_ROUND STEP_PER_ROUND
#define MOTOR2_STEP_PER_ROUND STEP_PER_ROUND
#define MOTOR3_STEP_PER_ROUND STEP_PER_ROUND
#define MOTOR4_STEP_PER_ROUND STEP_PER_ROUND
#define MOTOR5_STEP_PER_ROUND STEP_PER_ROUND

#define DRV_MICROSTEPPING 16
#define DRV1_MICROSTEPPING DRV_MICROSTEPPING
#define DRV2_MICROSTEPPING DRV_MICROSTEPPING
#define DRV3_MICROSTEPPING DRV_MICROSTEPPING
#define DRV4_MICROSTEPPING DRV_MICROSTEPPING
#define DRV5_MICROSTEPPING DRV_MICROSTEPPING

#define MAX_PLANNER_SPEED 20000
#define PLANNER_ACCELERATION 500

#define INPUT_REG_COUNT 2
#define OUTPUT_REG_COUNT 1

#define SERIAL_BAUD 115200

// 1 - STA
// 2 - AP
#define WIFI_MODE 2
#define WIFI_SSID "test"
#define WIFI_PASS "test"
#define AP_SSID "Manipulator"
#define AP_PASS "ManipulatorPass"